(cl:in-package fsd_common_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          FRAME_ID_NUM-VAL
          FRAME_ID_NUM
          LAT_ERROR_FRONT_AXIS-VAL
          LAT_ERROR_FRONT_AXIS
          LAT_ERROR_COG-VAL
          LAT_ERROR_COG
          LAT_ERROR_REAR_AXIS-VAL
          LAT_ERROR_REAR_AXIS
          YAW_ERROR_FRONT_AXIS-VAL
          YAW_ERROR_FRONT_AXIS
          YAW_ERROR_COG-VAL
          YAW_ERROR_COG
          YAW_ERROR_REAR_AXIS-VAL
          YAW_ERROR_REAR_AXIS
          YAW_RATE_ERROR-VAL
          YAW_RATE_ERROR
          STEERING_ERROR-VAL
          STEERING_ERROR
          VX_ERROR-VAL
          VX_ERROR
          VY_ERROR-VAL
          VY_ERROR
          SIDESLIP_ERROR-VAL
          SIDESLIP_ERROR
          MOTOR_TORQ_ERROR_LR-VAL
          MOTOR_TORQ_ERROR_LR
          MOTOR_TORQ_ERROR_RR-VAL
          MOTOR_TORQ_ERROR_RR
          MOTOR_SPEED_ERROR_LR-VAL
          MOTOR_SPEED_ERROR_LR
          MOTOR_SPEED_ERROR_RR-VAL
          MOTOR_SPEED_ERROR_RR
          ERROR1-VAL
          ERROR1
          ERROR2-VAL
          ERROR2
          ERROR3-VAL
          ERROR3
          ERROR4-VAL
          ERROR4
          YAW_REF-VAL
          YAW_REF
          YAW_REF_FRONT_AXIS-VAL
          YAW_REF_FRONT_AXIS
          YAW_REF_COG-VAL
          YAW_REF_COG
          YAW_REF_REAR_AXIS-VAL
          YAW_REF_REAR_AXIS
          CURVATURE_REF-VAL
          CURVATURE_REF
          CURVATURE_REF_FRONT_AXIS-VAL
          CURVATURE_REF_FRONT_AXIS
          CURVATURE_REF_COG-VAL
          CURVATURE_REF_COG
          CURVATURE_REF_REAR_AXIS-VAL
          CURVATURE_REF_REAR_AXIS
          VX_REF-VAL
          VX_REF
          VY_REF-VAL
          VY_REF
          AX_REF-VAL
          AX_REF
          AY_REF-VAL
          AY_REF
          REF1-VAL
          REF1
          REF2-VAL
          REF2
          REF3-VAL
          REF3
          REF4-VAL
          REF4
          STEERING_WITHOUT_COMPENSATION-VAL
          STEERING_WITHOUT_COMPENSATION
          STEERING_FEEDBACK-VAL
          STEERING_FEEDBACK
          STEERING_FEEDFORWARD-VAL
          STEERING_FEEDFORWARD
          LOOKFORWARD_LENGTH-VAL
          LOOKFORWARD_LENGTH
          YAW_RATE_PRE-VAL
          YAW_RATE_PRE
          TURNING_RADIUS-VAL
          TURNING_RADIUS
          ADHESION_COEFFICIENT_PRE-VAL
          ADHESION_COEFFICIENT_PRE
          SIDESLIP_PRE-VAL
          SIDESLIP_PRE
          SLIP_ANGLE_PRE_FL-VAL
          SLIP_ANGLE_PRE_FL
          SLIP_ANGLE_PRE_FR-VAL
          SLIP_ANGLE_PRE_FR
          SLIP_ANGLE_PRE_RL-VAL
          SLIP_ANGLE_PRE_RL
          SLIP_ANGLE_PRE_RR-VAL
          SLIP_ANGLE_PRE_RR
          NORM_FORCE_PRE_FL-VAL
          NORM_FORCE_PRE_FL
          NORM_FORCE_PRE_FR-VAL
          NORM_FORCE_PRE_FR
          NORM_FORCE_PRE_RL-VAL
          NORM_FORCE_PRE_RL
          NORM_FORCE_PRE_RR-VAL
          NORM_FORCE_PRE_RR
          ALGORITHM1-VAL
          ALGORITHM1
          ALGORITHM2-VAL
          ALGORITHM2
          ALGORITHM3-VAL
          ALGORITHM3
          ALGORITHM4-VAL
          ALGORITHM4
))