(cl:in-package fsd_common_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          FRAME_ID_NUM-VAL
          FRAME_ID_NUM
          LAT-VAL
          LAT
          LON-VAL
          LON
          H-VAL
          H
          VN-VAL
          VN
          VE-VAL
          VE
          VH-VAL
          VH
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          HEADING_ANGLE-VAL
          HEADING_ANGLE
          GYRO_X-VAL
          GYRO_X
          GYRO_Y-VAL
          GYRO_Y
          GYRO_Z-VAL
          GYRO_Z
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          STD_LAT-VAL
          STD_LAT
          STD_LON-VAL
          STD_LON
          STD_LOCALHEIGHT-VAL
          STD_LOCALHEIGHT
          NORTH_VELOCITY_STD-VAL
          NORTH_VELOCITY_STD
          EAST_VELOCITY_STD-VAL
          EAST_VELOCITY_STD
          GROUND_VELOCITY_STD-VAL
          GROUND_VELOCITY_STD
          ROLL_STD-VAL
          ROLL_STD
          PITCH_STD-VAL
          PITCH_STD
          STD_HEADING-VAL
          STD_HEADING
          STATUS-VAL
          STATUS
          GPSFLAG_POS-VAL
          GPSFLAG_POS
          GPS_WEEK_NUMBER-VAL
          GPS_WEEK_NUMBER
          ULLTIMESTAMP-VAL
          ULLTIMESTAMP
          TEMPERATURE-VAL
          TEMPERATURE
          CAR_STATUS-VAL
          CAR_STATUS
          GPSFLAG_HEADING-VAL
          GPSFLAG_HEADING
          NUMSV-VAL
          NUMSV
))