(cl:in-package fsd_common_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SPEED_TARGET-VAL
          SPEED_TARGET
          SPEED_ACTUAL-VAL
          SPEED_ACTUAL
          STEERING_ANGLE_TARGET-VAL
          STEERING_ANGLE_TARGET
          STEERING_ANGLE_ACTUAL-VAL
          STEERING_ANGLE_ACTUAL
          BRAKE_HYDR_TARGET-VAL
          BRAKE_HYDR_TARGET
          BRAKE_HYDR_ACTUAL-VAL
          BRAKE_HYDR_ACTUAL
          MOTOR_MOMENT_TARGET-VAL
          MOTOR_MOMENT_TARGET
          MOTOR_MOMENT_ACTUAL-VAL
          MOTOR_MOMENT_ACTUAL
          ACCELERATION_LONGITUDINAL-VAL
          ACCELERATION_LONGITUDINAL
          ACCELERATION_LATERAL-VAL
          ACCELERATION_LATERAL
          YAW_RATE-VAL
          YAW_RATE
))