(cl:in-package fsd_common_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          FRAME_ID_NUM-VAL
          FRAME_ID_NUM
          ULLTIMESTAMP-VAL
          ULLTIMESTAMP
          LAT-VAL
          LAT
          LON-VAL
          LON
          H-VAL
          H
          VN-VAL
          VN
          VE-VAL
          VE
          VH-VAL
          VH
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          GYRO_X-VAL
          GYRO_X
          GYRO_Y-VAL
          GYRO_Y
          GYRO_Z-VAL
          GYRO_Z
          STATE-VAL
          STATE
          GPSSTATE-VAL
          GPSSTATE
))