# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fsd_common_msgs/EchievMessage.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class EchievMessage(genpy.Message):
  _md5sum = "5074c8a56ee5217df1b459e01316b985"
  _type = "fsd_common_msgs/EchievMessage"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """#   echiev_perception ,message of echiev perception result 
Header header         # standard ROS message header
uint64 frame_id_num  
uint64 ullTimestamp
float64 lat
float64 lon
float32 h
float32 Vn
float32 Ve
float32 Vh
float32 roll
float32 Pitch
float32 yaw
float32 Acc_x
float32 Acc_y
float32 Acc_z
float32 Gyro_x
float32 Gyro_y
float32 Gyro_z
uint8 state
uint8 GPSState
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','frame_id_num','ullTimestamp','lat','lon','h','Vn','Ve','Vh','roll','Pitch','yaw','Acc_x','Acc_y','Acc_z','Gyro_x','Gyro_y','Gyro_z','state','GPSState']
  _slot_types = ['std_msgs/Header','uint64','uint64','float64','float64','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,frame_id_num,ullTimestamp,lat,lon,h,Vn,Ve,Vh,roll,Pitch,yaw,Acc_x,Acc_y,Acc_z,Gyro_x,Gyro_y,Gyro_z,state,GPSState

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EchievMessage, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.frame_id_num is None:
        self.frame_id_num = 0
      if self.ullTimestamp is None:
        self.ullTimestamp = 0
      if self.lat is None:
        self.lat = 0.
      if self.lon is None:
        self.lon = 0.
      if self.h is None:
        self.h = 0.
      if self.Vn is None:
        self.Vn = 0.
      if self.Ve is None:
        self.Ve = 0.
      if self.Vh is None:
        self.Vh = 0.
      if self.roll is None:
        self.roll = 0.
      if self.Pitch is None:
        self.Pitch = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.Acc_x is None:
        self.Acc_x = 0.
      if self.Acc_y is None:
        self.Acc_y = 0.
      if self.Acc_z is None:
        self.Acc_z = 0.
      if self.Gyro_x is None:
        self.Gyro_x = 0.
      if self.Gyro_y is None:
        self.Gyro_y = 0.
      if self.Gyro_z is None:
        self.Gyro_z = 0.
      if self.state is None:
        self.state = 0
      if self.GPSState is None:
        self.GPSState = 0
    else:
      self.header = std_msgs.msg.Header()
      self.frame_id_num = 0
      self.ullTimestamp = 0
      self.lat = 0.
      self.lon = 0.
      self.h = 0.
      self.Vn = 0.
      self.Ve = 0.
      self.Vh = 0.
      self.roll = 0.
      self.Pitch = 0.
      self.yaw = 0.
      self.Acc_x = 0.
      self.Acc_y = 0.
      self.Acc_z = 0.
      self.Gyro_x = 0.
      self.Gyro_y = 0.
      self.Gyro_z = 0.
      self.state = 0
      self.GPSState = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2Q2d13f2B().pack(_x.frame_id_num, _x.ullTimestamp, _x.lat, _x.lon, _x.h, _x.Vn, _x.Ve, _x.Vh, _x.roll, _x.Pitch, _x.yaw, _x.Acc_x, _x.Acc_y, _x.Acc_z, _x.Gyro_x, _x.Gyro_y, _x.Gyro_z, _x.state, _x.GPSState))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 86
      (_x.frame_id_num, _x.ullTimestamp, _x.lat, _x.lon, _x.h, _x.Vn, _x.Ve, _x.Vh, _x.roll, _x.Pitch, _x.yaw, _x.Acc_x, _x.Acc_y, _x.Acc_z, _x.Gyro_x, _x.Gyro_y, _x.Gyro_z, _x.state, _x.GPSState,) = _get_struct_2Q2d13f2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2Q2d13f2B().pack(_x.frame_id_num, _x.ullTimestamp, _x.lat, _x.lon, _x.h, _x.Vn, _x.Ve, _x.Vh, _x.roll, _x.Pitch, _x.yaw, _x.Acc_x, _x.Acc_y, _x.Acc_z, _x.Gyro_x, _x.Gyro_y, _x.Gyro_z, _x.state, _x.GPSState))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 86
      (_x.frame_id_num, _x.ullTimestamp, _x.lat, _x.lon, _x.h, _x.Vn, _x.Ve, _x.Vh, _x.roll, _x.Pitch, _x.yaw, _x.Acc_x, _x.Acc_y, _x.Acc_z, _x.Gyro_x, _x.Gyro_y, _x.Gyro_z, _x.state, _x.GPSState,) = _get_struct_2Q2d13f2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Q2d13f2B = None
def _get_struct_2Q2d13f2B():
    global _struct_2Q2d13f2B
    if _struct_2Q2d13f2B is None:
        _struct_2Q2d13f2B = struct.Struct("<2Q2d13f2B")
    return _struct_2Q2d13f2B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
