# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fsd_common_msgs/Feedback.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class Feedback(genpy.Message):
  _md5sum = "c7937c93e48c88e31894a7a84ffb18db"
  _type = "fsd_common_msgs/Feedback"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# car feedback data. 
Header header         # standard ROS message header
uint64 frame_id_num  
float32 wheel_speed_fl
float32 wheel_speed_fr
float32 wheel_speed_rl
float32 wheel_speed_rr
float32 motor_command_speed_rl
float32 motor_command_speed_rr
float32 motor_return_speed_rl
float32 motor_return_speed_rr
float32 motor_command_torq_rl
float32 motor_command_torq_rr
float32 motor_return_torq_rl
float32 motor_return_torq_rr

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','frame_id_num','wheel_speed_fl','wheel_speed_fr','wheel_speed_rl','wheel_speed_rr','motor_command_speed_rl','motor_command_speed_rr','motor_return_speed_rl','motor_return_speed_rr','motor_command_torq_rl','motor_command_torq_rr','motor_return_torq_rl','motor_return_torq_rr']
  _slot_types = ['std_msgs/Header','uint64','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,frame_id_num,wheel_speed_fl,wheel_speed_fr,wheel_speed_rl,wheel_speed_rr,motor_command_speed_rl,motor_command_speed_rr,motor_return_speed_rl,motor_return_speed_rr,motor_command_torq_rl,motor_command_torq_rr,motor_return_torq_rl,motor_return_torq_rr

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Feedback, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.frame_id_num is None:
        self.frame_id_num = 0
      if self.wheel_speed_fl is None:
        self.wheel_speed_fl = 0.
      if self.wheel_speed_fr is None:
        self.wheel_speed_fr = 0.
      if self.wheel_speed_rl is None:
        self.wheel_speed_rl = 0.
      if self.wheel_speed_rr is None:
        self.wheel_speed_rr = 0.
      if self.motor_command_speed_rl is None:
        self.motor_command_speed_rl = 0.
      if self.motor_command_speed_rr is None:
        self.motor_command_speed_rr = 0.
      if self.motor_return_speed_rl is None:
        self.motor_return_speed_rl = 0.
      if self.motor_return_speed_rr is None:
        self.motor_return_speed_rr = 0.
      if self.motor_command_torq_rl is None:
        self.motor_command_torq_rl = 0.
      if self.motor_command_torq_rr is None:
        self.motor_command_torq_rr = 0.
      if self.motor_return_torq_rl is None:
        self.motor_return_torq_rl = 0.
      if self.motor_return_torq_rr is None:
        self.motor_return_torq_rr = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.frame_id_num = 0
      self.wheel_speed_fl = 0.
      self.wheel_speed_fr = 0.
      self.wheel_speed_rl = 0.
      self.wheel_speed_rr = 0.
      self.motor_command_speed_rl = 0.
      self.motor_command_speed_rr = 0.
      self.motor_return_speed_rl = 0.
      self.motor_return_speed_rr = 0.
      self.motor_command_torq_rl = 0.
      self.motor_command_torq_rr = 0.
      self.motor_return_torq_rl = 0.
      self.motor_return_torq_rr = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Q12f().pack(_x.frame_id_num, _x.wheel_speed_fl, _x.wheel_speed_fr, _x.wheel_speed_rl, _x.wheel_speed_rr, _x.motor_command_speed_rl, _x.motor_command_speed_rr, _x.motor_return_speed_rl, _x.motor_return_speed_rr, _x.motor_command_torq_rl, _x.motor_command_torq_rr, _x.motor_return_torq_rl, _x.motor_return_torq_rr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.frame_id_num, _x.wheel_speed_fl, _x.wheel_speed_fr, _x.wheel_speed_rl, _x.wheel_speed_rr, _x.motor_command_speed_rl, _x.motor_command_speed_rr, _x.motor_return_speed_rl, _x.motor_return_speed_rr, _x.motor_command_torq_rl, _x.motor_command_torq_rr, _x.motor_return_torq_rl, _x.motor_return_torq_rr,) = _get_struct_Q12f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Q12f().pack(_x.frame_id_num, _x.wheel_speed_fl, _x.wheel_speed_fr, _x.wheel_speed_rl, _x.wheel_speed_rr, _x.motor_command_speed_rl, _x.motor_command_speed_rr, _x.motor_return_speed_rl, _x.motor_return_speed_rr, _x.motor_command_torq_rl, _x.motor_command_torq_rr, _x.motor_return_torq_rl, _x.motor_return_torq_rr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.frame_id_num, _x.wheel_speed_fl, _x.wheel_speed_fr, _x.wheel_speed_rl, _x.wheel_speed_rr, _x.motor_command_speed_rl, _x.motor_command_speed_rr, _x.motor_return_speed_rl, _x.motor_return_speed_rr, _x.motor_command_torq_rl, _x.motor_command_torq_rr, _x.motor_return_torq_rl, _x.motor_return_torq_rr,) = _get_struct_Q12f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_Q12f = None
def _get_struct_Q12f():
    global _struct_Q12f
    if _struct_Q12f is None:
        _struct_Q12f = struct.Struct("<Q12f")
    return _struct_Q12f
