# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fsd_common_msgs/Map.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import fsd_common_msgs.msg
import geometry_msgs.msg
import std_msgs.msg

class Map(genpy.Message):
  _md5sum = "84705d16c4fc49753827594412fe4d4a"
  _type = "fsd_common_msgs/Map"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

fsd_common_msgs/Cone[] cone_yellow
fsd_common_msgs/Cone[] cone_blue
fsd_common_msgs/Cone[] cone_red
fsd_common_msgs/Cone[] cone_unknown
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: fsd_common_msgs/Cone
geometry_msgs/Point position  	      # coordinate of cone in [x, y]
std_msgs/String color                 # color of cone, 'b' = blue, 'y' = yellow, 'o' = orange
std_msgs/Float32 poseConfidence   	      # confidence of cone detect
std_msgs/Float32 colorConfidence   	      # confidence of cone detect

#uint8 cluster
#uint8 pointType
#uint8 pts
#uint8 visited
#uint8[] corepts

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: std_msgs/String
string data

================================================================================
MSG: std_msgs/Float32
float32 data"""
  __slots__ = ['header','cone_yellow','cone_blue','cone_red','cone_unknown']
  _slot_types = ['std_msgs/Header','fsd_common_msgs/Cone[]','fsd_common_msgs/Cone[]','fsd_common_msgs/Cone[]','fsd_common_msgs/Cone[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,cone_yellow,cone_blue,cone_red,cone_unknown

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Map, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cone_yellow is None:
        self.cone_yellow = []
      if self.cone_blue is None:
        self.cone_blue = []
      if self.cone_red is None:
        self.cone_red = []
      if self.cone_unknown is None:
        self.cone_unknown = []
    else:
      self.header = std_msgs.msg.Header()
      self.cone_yellow = []
      self.cone_blue = []
      self.cone_red = []
      self.cone_unknown = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.cone_yellow)
      buff.write(_struct_I.pack(length))
      for val1 in self.cone_yellow:
        _v1 = val1.position
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v2 = val1.color
        _x = _v2.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v3 = val1.poseConfidence
        _x = _v3.data
        buff.write(_get_struct_f().pack(_x))
        _v4 = val1.colorConfidence
        _x = _v4.data
        buff.write(_get_struct_f().pack(_x))
      length = len(self.cone_blue)
      buff.write(_struct_I.pack(length))
      for val1 in self.cone_blue:
        _v5 = val1.position
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v6 = val1.color
        _x = _v6.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v7 = val1.poseConfidence
        _x = _v7.data
        buff.write(_get_struct_f().pack(_x))
        _v8 = val1.colorConfidence
        _x = _v8.data
        buff.write(_get_struct_f().pack(_x))
      length = len(self.cone_red)
      buff.write(_struct_I.pack(length))
      for val1 in self.cone_red:
        _v9 = val1.position
        _x = _v9
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v10 = val1.color
        _x = _v10.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v11 = val1.poseConfidence
        _x = _v11.data
        buff.write(_get_struct_f().pack(_x))
        _v12 = val1.colorConfidence
        _x = _v12.data
        buff.write(_get_struct_f().pack(_x))
      length = len(self.cone_unknown)
      buff.write(_struct_I.pack(length))
      for val1 in self.cone_unknown:
        _v13 = val1.position
        _x = _v13
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v14 = val1.color
        _x = _v14.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v15 = val1.poseConfidence
        _x = _v15.data
        buff.write(_get_struct_f().pack(_x))
        _v16 = val1.colorConfidence
        _x = _v16.data
        buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cone_yellow is None:
        self.cone_yellow = None
      if self.cone_blue is None:
        self.cone_blue = None
      if self.cone_red is None:
        self.cone_red = None
      if self.cone_unknown is None:
        self.cone_unknown = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cone_yellow = []
      for i in range(0, length):
        val1 = fsd_common_msgs.msg.Cone()
        _v17 = val1.position
        _x = _v17
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v18 = val1.color
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v18.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v18.data = str[start:end]
        _v19 = val1.poseConfidence
        start = end
        end += 4
        (_v19.data,) = _get_struct_f().unpack(str[start:end])
        _v20 = val1.colorConfidence
        start = end
        end += 4
        (_v20.data,) = _get_struct_f().unpack(str[start:end])
        self.cone_yellow.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cone_blue = []
      for i in range(0, length):
        val1 = fsd_common_msgs.msg.Cone()
        _v21 = val1.position
        _x = _v21
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v22 = val1.color
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v22.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v22.data = str[start:end]
        _v23 = val1.poseConfidence
        start = end
        end += 4
        (_v23.data,) = _get_struct_f().unpack(str[start:end])
        _v24 = val1.colorConfidence
        start = end
        end += 4
        (_v24.data,) = _get_struct_f().unpack(str[start:end])
        self.cone_blue.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cone_red = []
      for i in range(0, length):
        val1 = fsd_common_msgs.msg.Cone()
        _v25 = val1.position
        _x = _v25
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v26 = val1.color
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v26.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v26.data = str[start:end]
        _v27 = val1.poseConfidence
        start = end
        end += 4
        (_v27.data,) = _get_struct_f().unpack(str[start:end])
        _v28 = val1.colorConfidence
        start = end
        end += 4
        (_v28.data,) = _get_struct_f().unpack(str[start:end])
        self.cone_red.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cone_unknown = []
      for i in range(0, length):
        val1 = fsd_common_msgs.msg.Cone()
        _v29 = val1.position
        _x = _v29
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v30 = val1.color
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v30.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v30.data = str[start:end]
        _v31 = val1.poseConfidence
        start = end
        end += 4
        (_v31.data,) = _get_struct_f().unpack(str[start:end])
        _v32 = val1.colorConfidence
        start = end
        end += 4
        (_v32.data,) = _get_struct_f().unpack(str[start:end])
        self.cone_unknown.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.cone_yellow)
      buff.write(_struct_I.pack(length))
      for val1 in self.cone_yellow:
        _v33 = val1.position
        _x = _v33
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v34 = val1.color
        _x = _v34.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v35 = val1.poseConfidence
        _x = _v35.data
        buff.write(_get_struct_f().pack(_x))
        _v36 = val1.colorConfidence
        _x = _v36.data
        buff.write(_get_struct_f().pack(_x))
      length = len(self.cone_blue)
      buff.write(_struct_I.pack(length))
      for val1 in self.cone_blue:
        _v37 = val1.position
        _x = _v37
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v38 = val1.color
        _x = _v38.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v39 = val1.poseConfidence
        _x = _v39.data
        buff.write(_get_struct_f().pack(_x))
        _v40 = val1.colorConfidence
        _x = _v40.data
        buff.write(_get_struct_f().pack(_x))
      length = len(self.cone_red)
      buff.write(_struct_I.pack(length))
      for val1 in self.cone_red:
        _v41 = val1.position
        _x = _v41
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v42 = val1.color
        _x = _v42.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v43 = val1.poseConfidence
        _x = _v43.data
        buff.write(_get_struct_f().pack(_x))
        _v44 = val1.colorConfidence
        _x = _v44.data
        buff.write(_get_struct_f().pack(_x))
      length = len(self.cone_unknown)
      buff.write(_struct_I.pack(length))
      for val1 in self.cone_unknown:
        _v45 = val1.position
        _x = _v45
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v46 = val1.color
        _x = _v46.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v47 = val1.poseConfidence
        _x = _v47.data
        buff.write(_get_struct_f().pack(_x))
        _v48 = val1.colorConfidence
        _x = _v48.data
        buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cone_yellow is None:
        self.cone_yellow = None
      if self.cone_blue is None:
        self.cone_blue = None
      if self.cone_red is None:
        self.cone_red = None
      if self.cone_unknown is None:
        self.cone_unknown = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cone_yellow = []
      for i in range(0, length):
        val1 = fsd_common_msgs.msg.Cone()
        _v49 = val1.position
        _x = _v49
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v50 = val1.color
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v50.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v50.data = str[start:end]
        _v51 = val1.poseConfidence
        start = end
        end += 4
        (_v51.data,) = _get_struct_f().unpack(str[start:end])
        _v52 = val1.colorConfidence
        start = end
        end += 4
        (_v52.data,) = _get_struct_f().unpack(str[start:end])
        self.cone_yellow.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cone_blue = []
      for i in range(0, length):
        val1 = fsd_common_msgs.msg.Cone()
        _v53 = val1.position
        _x = _v53
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v54 = val1.color
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v54.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v54.data = str[start:end]
        _v55 = val1.poseConfidence
        start = end
        end += 4
        (_v55.data,) = _get_struct_f().unpack(str[start:end])
        _v56 = val1.colorConfidence
        start = end
        end += 4
        (_v56.data,) = _get_struct_f().unpack(str[start:end])
        self.cone_blue.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cone_red = []
      for i in range(0, length):
        val1 = fsd_common_msgs.msg.Cone()
        _v57 = val1.position
        _x = _v57
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v58 = val1.color
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v58.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v58.data = str[start:end]
        _v59 = val1.poseConfidence
        start = end
        end += 4
        (_v59.data,) = _get_struct_f().unpack(str[start:end])
        _v60 = val1.colorConfidence
        start = end
        end += 4
        (_v60.data,) = _get_struct_f().unpack(str[start:end])
        self.cone_red.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cone_unknown = []
      for i in range(0, length):
        val1 = fsd_common_msgs.msg.Cone()
        _v61 = val1.position
        _x = _v61
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v62 = val1.color
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v62.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v62.data = str[start:end]
        _v63 = val1.poseConfidence
        start = end
        end += 4
        (_v63.data,) = _get_struct_f().unpack(str[start:end])
        _v64 = val1.colorConfidence
        start = end
        end += 4
        (_v64.data,) = _get_struct_f().unpack(str[start:end])
        self.cone_unknown.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
