# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fsd_common_msgs/YoloCone.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class YoloCone(genpy.Message):
  _md5sum = "f6cb33486e6643502ddbc8297e8d043a"
  _type = "fsd_common_msgs/YoloCone"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Float32 x                  # center x
std_msgs/Float32 y                  # center y
std_msgs/Float32 width              # width
std_msgs/Float32 height             # height

std_msgs/String color                 # color of cone, 'r' = red, 'b' = blue, 'y' = yellow
std_msgs/Float32 colorConfidence   	      # confidence of cone detect

================================================================================
MSG: std_msgs/Float32
float32 data
================================================================================
MSG: std_msgs/String
string data
"""
  __slots__ = ['x','y','width','height','color','colorConfidence']
  _slot_types = ['std_msgs/Float32','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32','std_msgs/String','std_msgs/Float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,width,height,color,colorConfidence

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(YoloCone, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = std_msgs.msg.Float32()
      if self.y is None:
        self.y = std_msgs.msg.Float32()
      if self.width is None:
        self.width = std_msgs.msg.Float32()
      if self.height is None:
        self.height = std_msgs.msg.Float32()
      if self.color is None:
        self.color = std_msgs.msg.String()
      if self.colorConfidence is None:
        self.colorConfidence = std_msgs.msg.Float32()
    else:
      self.x = std_msgs.msg.Float32()
      self.y = std_msgs.msg.Float32()
      self.width = std_msgs.msg.Float32()
      self.height = std_msgs.msg.Float32()
      self.color = std_msgs.msg.String()
      self.colorConfidence = std_msgs.msg.Float32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.x.data, _x.y.data, _x.width.data, _x.height.data))
      _x = self.color.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.colorConfidence.data
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.x is None:
        self.x = std_msgs.msg.Float32()
      if self.y is None:
        self.y = std_msgs.msg.Float32()
      if self.width is None:
        self.width = std_msgs.msg.Float32()
      if self.height is None:
        self.height = std_msgs.msg.Float32()
      if self.color is None:
        self.color = std_msgs.msg.String()
      if self.colorConfidence is None:
        self.colorConfidence = std_msgs.msg.Float32()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.x.data, _x.y.data, _x.width.data, _x.height.data,) = _get_struct_4f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.color.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.color.data = str[start:end]
      start = end
      end += 4
      (self.colorConfidence.data,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.x.data, _x.y.data, _x.width.data, _x.height.data))
      _x = self.color.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.colorConfidence.data
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.x is None:
        self.x = std_msgs.msg.Float32()
      if self.y is None:
        self.y = std_msgs.msg.Float32()
      if self.width is None:
        self.width = std_msgs.msg.Float32()
      if self.height is None:
        self.height = std_msgs.msg.Float32()
      if self.color is None:
        self.color = std_msgs.msg.String()
      if self.colorConfidence is None:
        self.colorConfidence = std_msgs.msg.Float32()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.x.data, _x.y.data, _x.width.data, _x.height.data,) = _get_struct_4f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.color.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.color.data = str[start:end]
      start = end
      end += 4
      (self.colorConfidence.data,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
