# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from fsd_common_msgs/YoloConeDetectionsTrack.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import fsd_common_msgs.msg
import geometry_msgs.msg
import std_msgs.msg

class YoloConeDetectionsTrack(genpy.Message):
  _md5sum = "e97881ef9e11eb60ad6c895ff672af98"
  _type = "fsd_common_msgs/YoloConeDetectionsTrack"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

fsd_common_msgs/YoloConeTrack[] cone_detections
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: fsd_common_msgs/YoloConeTrack
std_msgs/Float32 x                  # center x
std_msgs/Float32 y                  # center y
std_msgs/Float32 width              # width
std_msgs/Float32 height             # height

std_msgs/String color                 # color of cone, 'r' = red, 'b' = blue, 'y' = yellow
std_msgs/Float32 colorConfidence   	      # confidence of cone detect

geometry_msgs/Point position # 3d position with (x,y,z)
std_msgs/Float32 poseConfidence

std_msgs/UInt8 tracking_id
std_msgs/String tracking_state # OFF, OK, SEARCHING, TERMINATE
std_msgs/UInt8 missing_frams
================================================================================
MSG: std_msgs/Float32
float32 data
================================================================================
MSG: std_msgs/String
string data

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: std_msgs/UInt8
uint8 data
"""
  __slots__ = ['header','cone_detections']
  _slot_types = ['std_msgs/Header','fsd_common_msgs/YoloConeTrack[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,cone_detections

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(YoloConeDetectionsTrack, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cone_detections is None:
        self.cone_detections = []
    else:
      self.header = std_msgs.msg.Header()
      self.cone_detections = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.cone_detections)
      buff.write(_struct_I.pack(length))
      for val1 in self.cone_detections:
        _v1 = val1.x
        _x = _v1.data
        buff.write(_get_struct_f().pack(_x))
        _v2 = val1.y
        _x = _v2.data
        buff.write(_get_struct_f().pack(_x))
        _v3 = val1.width
        _x = _v3.data
        buff.write(_get_struct_f().pack(_x))
        _v4 = val1.height
        _x = _v4.data
        buff.write(_get_struct_f().pack(_x))
        _v5 = val1.color
        _x = _v5.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v6 = val1.colorConfidence
        _x = _v6.data
        buff.write(_get_struct_f().pack(_x))
        _v7 = val1.position
        _x = _v7
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v8 = val1.poseConfidence
        _x = _v8.data
        buff.write(_get_struct_f().pack(_x))
        _v9 = val1.tracking_id
        _x = _v9.data
        buff.write(_get_struct_B().pack(_x))
        _v10 = val1.tracking_state
        _x = _v10.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v11 = val1.missing_frams
        _x = _v11.data
        buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cone_detections is None:
        self.cone_detections = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cone_detections = []
      for i in range(0, length):
        val1 = fsd_common_msgs.msg.YoloConeTrack()
        _v12 = val1.x
        start = end
        end += 4
        (_v12.data,) = _get_struct_f().unpack(str[start:end])
        _v13 = val1.y
        start = end
        end += 4
        (_v13.data,) = _get_struct_f().unpack(str[start:end])
        _v14 = val1.width
        start = end
        end += 4
        (_v14.data,) = _get_struct_f().unpack(str[start:end])
        _v15 = val1.height
        start = end
        end += 4
        (_v15.data,) = _get_struct_f().unpack(str[start:end])
        _v16 = val1.color
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v16.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v16.data = str[start:end]
        _v17 = val1.colorConfidence
        start = end
        end += 4
        (_v17.data,) = _get_struct_f().unpack(str[start:end])
        _v18 = val1.position
        _x = _v18
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v19 = val1.poseConfidence
        start = end
        end += 4
        (_v19.data,) = _get_struct_f().unpack(str[start:end])
        _v20 = val1.tracking_id
        start = end
        end += 1
        (_v20.data,) = _get_struct_B().unpack(str[start:end])
        _v21 = val1.tracking_state
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v21.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v21.data = str[start:end]
        _v22 = val1.missing_frams
        start = end
        end += 1
        (_v22.data,) = _get_struct_B().unpack(str[start:end])
        self.cone_detections.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.cone_detections)
      buff.write(_struct_I.pack(length))
      for val1 in self.cone_detections:
        _v23 = val1.x
        _x = _v23.data
        buff.write(_get_struct_f().pack(_x))
        _v24 = val1.y
        _x = _v24.data
        buff.write(_get_struct_f().pack(_x))
        _v25 = val1.width
        _x = _v25.data
        buff.write(_get_struct_f().pack(_x))
        _v26 = val1.height
        _x = _v26.data
        buff.write(_get_struct_f().pack(_x))
        _v27 = val1.color
        _x = _v27.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v28 = val1.colorConfidence
        _x = _v28.data
        buff.write(_get_struct_f().pack(_x))
        _v29 = val1.position
        _x = _v29
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v30 = val1.poseConfidence
        _x = _v30.data
        buff.write(_get_struct_f().pack(_x))
        _v31 = val1.tracking_id
        _x = _v31.data
        buff.write(_get_struct_B().pack(_x))
        _v32 = val1.tracking_state
        _x = _v32.data
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v33 = val1.missing_frams
        _x = _v33.data
        buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.cone_detections is None:
        self.cone_detections = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.cone_detections = []
      for i in range(0, length):
        val1 = fsd_common_msgs.msg.YoloConeTrack()
        _v34 = val1.x
        start = end
        end += 4
        (_v34.data,) = _get_struct_f().unpack(str[start:end])
        _v35 = val1.y
        start = end
        end += 4
        (_v35.data,) = _get_struct_f().unpack(str[start:end])
        _v36 = val1.width
        start = end
        end += 4
        (_v36.data,) = _get_struct_f().unpack(str[start:end])
        _v37 = val1.height
        start = end
        end += 4
        (_v37.data,) = _get_struct_f().unpack(str[start:end])
        _v38 = val1.color
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v38.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v38.data = str[start:end]
        _v39 = val1.colorConfidence
        start = end
        end += 4
        (_v39.data,) = _get_struct_f().unpack(str[start:end])
        _v40 = val1.position
        _x = _v40
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v41 = val1.poseConfidence
        start = end
        end += 4
        (_v41.data,) = _get_struct_f().unpack(str[start:end])
        _v42 = val1.tracking_id
        start = end
        end += 1
        (_v42.data,) = _get_struct_B().unpack(str[start:end])
        _v43 = val1.tracking_state
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v43.data = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v43.data = str[start:end]
        _v44 = val1.missing_frams
        start = end
        end += 1
        (_v44.data,) = _get_struct_B().unpack(str[start:end])
        self.cone_detections.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
