// Generated by gencpp from file fsd_common_msgs/CanFrames.msg
// DO NOT EDIT!


#ifndef FSD_COMMON_MSGS_MESSAGE_CANFRAMES_H
#define FSD_COMMON_MSGS_MESSAGE_CANFRAMES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <can_msgs/Frame.h>

namespace fsd_common_msgs
{
template <class ContainerAllocator>
struct CanFrames_
{
  typedef CanFrames_<ContainerAllocator> Type;

  CanFrames_()
    : header()
    , Frames()  {
    }
  CanFrames_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , Frames(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::can_msgs::Frame_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::can_msgs::Frame_<ContainerAllocator> >> _Frames_type;
  _Frames_type Frames;





  typedef boost::shared_ptr< ::fsd_common_msgs::CanFrames_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fsd_common_msgs::CanFrames_<ContainerAllocator> const> ConstPtr;

}; // struct CanFrames_

typedef ::fsd_common_msgs::CanFrames_<std::allocator<void> > CanFrames;

typedef boost::shared_ptr< ::fsd_common_msgs::CanFrames > CanFramesPtr;
typedef boost::shared_ptr< ::fsd_common_msgs::CanFrames const> CanFramesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fsd_common_msgs::CanFrames_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fsd_common_msgs::CanFrames_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fsd_common_msgs::CanFrames_<ContainerAllocator1> & lhs, const ::fsd_common_msgs::CanFrames_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.Frames == rhs.Frames;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fsd_common_msgs::CanFrames_<ContainerAllocator1> & lhs, const ::fsd_common_msgs::CanFrames_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fsd_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fsd_common_msgs::CanFrames_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fsd_common_msgs::CanFrames_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsd_common_msgs::CanFrames_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsd_common_msgs::CanFrames_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsd_common_msgs::CanFrames_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsd_common_msgs::CanFrames_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fsd_common_msgs::CanFrames_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c94db952be9e0d7fac82c0d8b6f65da";
  }

  static const char* value(const ::fsd_common_msgs::CanFrames_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c94db952be9e0d7ULL;
  static const uint64_t static_value2 = 0xfac82c0d8b6f65daULL;
};

template<class ContainerAllocator>
struct DataType< ::fsd_common_msgs::CanFrames_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fsd_common_msgs/CanFrames";
  }

  static const char* value(const ::fsd_common_msgs::CanFrames_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fsd_common_msgs::CanFrames_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"can_msgs/Frame[] Frames\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: can_msgs/Frame\n"
"Header header\n"
"uint32 id\n"
"bool is_rtr\n"
"bool is_extended\n"
"bool is_error\n"
"uint8 dlc\n"
"uint8[8] data\n"
;
  }

  static const char* value(const ::fsd_common_msgs::CanFrames_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fsd_common_msgs::CanFrames_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.Frames);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CanFrames_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fsd_common_msgs::CanFrames_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fsd_common_msgs::CanFrames_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "Frames[]" << std::endl;
    for (size_t i = 0; i < v.Frames.size(); ++i)
    {
      s << indent << "  Frames[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::can_msgs::Frame_<ContainerAllocator> >::stream(s, indent + "    ", v.Frames[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FSD_COMMON_MSGS_MESSAGE_CANFRAMES_H
