// Generated by gencpp from file fsd_common_msgs/Map.msg
// DO NOT EDIT!


#ifndef FSD_COMMON_MSGS_MESSAGE_MAP_H
#define FSD_COMMON_MSGS_MESSAGE_MAP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <fsd_common_msgs/Cone.h>
#include <fsd_common_msgs/Cone.h>
#include <fsd_common_msgs/Cone.h>
#include <fsd_common_msgs/Cone.h>

namespace fsd_common_msgs
{
template <class ContainerAllocator>
struct Map_
{
  typedef Map_<ContainerAllocator> Type;

  Map_()
    : header()
    , cone_yellow()
    , cone_blue()
    , cone_red()
    , cone_unknown()  {
    }
  Map_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cone_yellow(_alloc)
    , cone_blue(_alloc)
    , cone_red(_alloc)
    , cone_unknown(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::fsd_common_msgs::Cone_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::fsd_common_msgs::Cone_<ContainerAllocator> >> _cone_yellow_type;
  _cone_yellow_type cone_yellow;

   typedef std::vector< ::fsd_common_msgs::Cone_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::fsd_common_msgs::Cone_<ContainerAllocator> >> _cone_blue_type;
  _cone_blue_type cone_blue;

   typedef std::vector< ::fsd_common_msgs::Cone_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::fsd_common_msgs::Cone_<ContainerAllocator> >> _cone_red_type;
  _cone_red_type cone_red;

   typedef std::vector< ::fsd_common_msgs::Cone_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::fsd_common_msgs::Cone_<ContainerAllocator> >> _cone_unknown_type;
  _cone_unknown_type cone_unknown;





  typedef boost::shared_ptr< ::fsd_common_msgs::Map_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fsd_common_msgs::Map_<ContainerAllocator> const> ConstPtr;

}; // struct Map_

typedef ::fsd_common_msgs::Map_<std::allocator<void> > Map;

typedef boost::shared_ptr< ::fsd_common_msgs::Map > MapPtr;
typedef boost::shared_ptr< ::fsd_common_msgs::Map const> MapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fsd_common_msgs::Map_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fsd_common_msgs::Map_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fsd_common_msgs::Map_<ContainerAllocator1> & lhs, const ::fsd_common_msgs::Map_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cone_yellow == rhs.cone_yellow &&
    lhs.cone_blue == rhs.cone_blue &&
    lhs.cone_red == rhs.cone_red &&
    lhs.cone_unknown == rhs.cone_unknown;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fsd_common_msgs::Map_<ContainerAllocator1> & lhs, const ::fsd_common_msgs::Map_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fsd_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fsd_common_msgs::Map_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fsd_common_msgs::Map_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsd_common_msgs::Map_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsd_common_msgs::Map_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsd_common_msgs::Map_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsd_common_msgs::Map_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fsd_common_msgs::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84705d16c4fc49753827594412fe4d4a";
  }

  static const char* value(const ::fsd_common_msgs::Map_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84705d16c4fc4975ULL;
  static const uint64_t static_value2 = 0x3827594412fe4d4aULL;
};

template<class ContainerAllocator>
struct DataType< ::fsd_common_msgs::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fsd_common_msgs/Map";
  }

  static const char* value(const ::fsd_common_msgs::Map_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fsd_common_msgs::Map_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"fsd_common_msgs/Cone[] cone_yellow\n"
"fsd_common_msgs/Cone[] cone_blue\n"
"fsd_common_msgs/Cone[] cone_red\n"
"fsd_common_msgs/Cone[] cone_unknown\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: fsd_common_msgs/Cone\n"
"geometry_msgs/Point position  	      # coordinate of cone in [x, y]\n"
"std_msgs/String color                 # color of cone, 'b' = blue, 'y' = yellow, 'o' = orange\n"
"std_msgs/Float32 poseConfidence   	      # confidence of cone detect\n"
"std_msgs/Float32 colorConfidence   	      # confidence of cone detect\n"
"\n"
"#uint8 cluster\n"
"#uint8 pointType\n"
"#uint8 pts\n"
"#uint8 visited\n"
"#uint8[] corepts\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
;
  }

  static const char* value(const ::fsd_common_msgs::Map_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fsd_common_msgs::Map_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cone_yellow);
      stream.next(m.cone_blue);
      stream.next(m.cone_red);
      stream.next(m.cone_unknown);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Map_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fsd_common_msgs::Map_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fsd_common_msgs::Map_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cone_yellow[]" << std::endl;
    for (size_t i = 0; i < v.cone_yellow.size(); ++i)
    {
      s << indent << "  cone_yellow[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fsd_common_msgs::Cone_<ContainerAllocator> >::stream(s, indent + "    ", v.cone_yellow[i]);
    }
    s << indent << "cone_blue[]" << std::endl;
    for (size_t i = 0; i < v.cone_blue.size(); ++i)
    {
      s << indent << "  cone_blue[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fsd_common_msgs::Cone_<ContainerAllocator> >::stream(s, indent + "    ", v.cone_blue[i]);
    }
    s << indent << "cone_red[]" << std::endl;
    for (size_t i = 0; i < v.cone_red.size(); ++i)
    {
      s << indent << "  cone_red[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fsd_common_msgs::Cone_<ContainerAllocator> >::stream(s, indent + "    ", v.cone_red[i]);
    }
    s << indent << "cone_unknown[]" << std::endl;
    for (size_t i = 0; i < v.cone_unknown.size(); ++i)
    {
      s << indent << "  cone_unknown[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fsd_common_msgs::Cone_<ContainerAllocator> >::stream(s, indent + "    ", v.cone_unknown[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FSD_COMMON_MSGS_MESSAGE_MAP_H
