// Generated by gencpp from file fsd_common_msgs/ResAndAmi.msg
// DO NOT EDIT!


#ifndef FSD_COMMON_MSGS_MESSAGE_RESANDAMI_H
#define FSD_COMMON_MSGS_MESSAGE_RESANDAMI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace fsd_common_msgs
{
template <class ContainerAllocator>
struct ResAndAmi_
{
  typedef ResAndAmi_<ContainerAllocator> Type;

  ResAndAmi_()
    : header()
    , resState(0)
    , mission()  {
    }
  ResAndAmi_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , resState(0)
    , mission(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _resState_type;
  _resState_type resState;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mission_type;
  _mission_type mission;





  typedef boost::shared_ptr< ::fsd_common_msgs::ResAndAmi_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fsd_common_msgs::ResAndAmi_<ContainerAllocator> const> ConstPtr;

}; // struct ResAndAmi_

typedef ::fsd_common_msgs::ResAndAmi_<std::allocator<void> > ResAndAmi;

typedef boost::shared_ptr< ::fsd_common_msgs::ResAndAmi > ResAndAmiPtr;
typedef boost::shared_ptr< ::fsd_common_msgs::ResAndAmi const> ResAndAmiConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fsd_common_msgs::ResAndAmi_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fsd_common_msgs::ResAndAmi_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fsd_common_msgs::ResAndAmi_<ContainerAllocator1> & lhs, const ::fsd_common_msgs::ResAndAmi_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.resState == rhs.resState &&
    lhs.mission == rhs.mission;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fsd_common_msgs::ResAndAmi_<ContainerAllocator1> & lhs, const ::fsd_common_msgs::ResAndAmi_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fsd_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fsd_common_msgs::ResAndAmi_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fsd_common_msgs::ResAndAmi_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsd_common_msgs::ResAndAmi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsd_common_msgs::ResAndAmi_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsd_common_msgs::ResAndAmi_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsd_common_msgs::ResAndAmi_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fsd_common_msgs::ResAndAmi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4dcace2ffbf47fc79a4d8e0bd59de0a";
  }

  static const char* value(const ::fsd_common_msgs::ResAndAmi_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4dcace2ffbf47fcULL;
  static const uint64_t static_value2 = 0x79a4d8e0bd59de0aULL;
};

template<class ContainerAllocator>
struct DataType< ::fsd_common_msgs::ResAndAmi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fsd_common_msgs/ResAndAmi";
  }

  static const char* value(const ::fsd_common_msgs::ResAndAmi_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fsd_common_msgs::ResAndAmi_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Header\n"
"std_msgs/Header header\n"
"uint8 resState 		#指示res状态，1代表“go”信号\n"
"string mission          #指示AMI选择的无人驾驶任务。0.inspection;1.ebs_test;2.acceleration;3.skidpad;4.trackdrive\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::fsd_common_msgs::ResAndAmi_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fsd_common_msgs::ResAndAmi_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.resState);
      stream.next(m.mission);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResAndAmi_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fsd_common_msgs::ResAndAmi_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fsd_common_msgs::ResAndAmi_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "resState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.resState);
    s << indent << "mission: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mission);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FSD_COMMON_MSGS_MESSAGE_RESANDAMI_H
