// Generated by gencpp from file fsd_common_msgs/SkidpadGlobalCenterLine.msg
// DO NOT EDIT!


#ifndef FSD_COMMON_MSGS_MESSAGE_SKIDPADGLOBALCENTERLINE_H
#define FSD_COMMON_MSGS_MESSAGE_SKIDPADGLOBALCENTERLINE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace fsd_common_msgs
{
template <class ContainerAllocator>
struct SkidpadGlobalCenterLine_
{
  typedef SkidpadGlobalCenterLine_<ContainerAllocator> Type;

  SkidpadGlobalCenterLine_()
    : global_path()
    , isReachMid(false)  {
    }
  SkidpadGlobalCenterLine_(const ContainerAllocator& _alloc)
    : global_path(_alloc)
    , isReachMid(false)  {
  (void)_alloc;
    }



   typedef  ::nav_msgs::Path_<ContainerAllocator>  _global_path_type;
  _global_path_type global_path;

   typedef uint8_t _isReachMid_type;
  _isReachMid_type isReachMid;





  typedef boost::shared_ptr< ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator> const> ConstPtr;

}; // struct SkidpadGlobalCenterLine_

typedef ::fsd_common_msgs::SkidpadGlobalCenterLine_<std::allocator<void> > SkidpadGlobalCenterLine;

typedef boost::shared_ptr< ::fsd_common_msgs::SkidpadGlobalCenterLine > SkidpadGlobalCenterLinePtr;
typedef boost::shared_ptr< ::fsd_common_msgs::SkidpadGlobalCenterLine const> SkidpadGlobalCenterLineConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator1> & lhs, const ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator2> & rhs)
{
  return lhs.global_path == rhs.global_path &&
    lhs.isReachMid == rhs.isReachMid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator1> & lhs, const ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fsd_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f5dd51f67a61514e402c1272e9d512a";
  }

  static const char* value(const ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f5dd51f67a61514ULL;
  static const uint64_t static_value2 = 0xe402c1272e9d512aULL;
};

template<class ContainerAllocator>
struct DataType< ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fsd_common_msgs/SkidpadGlobalCenterLine";
  }

  static const char* value(const ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_msgs/Path global_path\n"
"bool isReachMid\n"
"================================================================================\n"
"MSG: nav_msgs/Path\n"
"#An array of poses that represents a Path for a robot to follow\n"
"Header header\n"
"geometry_msgs/PoseStamped[] poses\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.global_path);
      stream.next(m.isReachMid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SkidpadGlobalCenterLine_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fsd_common_msgs::SkidpadGlobalCenterLine_<ContainerAllocator>& v)
  {
    s << indent << "global_path: ";
    s << std::endl;
    Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.global_path);
    s << indent << "isReachMid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isReachMid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FSD_COMMON_MSGS_MESSAGE_SKIDPADGLOBALCENTERLINE_H
