// Generated by gencpp from file fsd_common_msgs/YoloConeDetections.msg
// DO NOT EDIT!


#ifndef FSD_COMMON_MSGS_MESSAGE_YOLOCONEDETECTIONS_H
#define FSD_COMMON_MSGS_MESSAGE_YOLOCONEDETECTIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Header.h>
#include <fsd_common_msgs/YoloCone.h>

namespace fsd_common_msgs
{
template <class ContainerAllocator>
struct YoloConeDetections_
{
  typedef YoloConeDetections_<ContainerAllocator> Type;

  YoloConeDetections_()
    : header()
    , image_header()
    , cone_detections()  {
    }
  YoloConeDetections_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image_header(_alloc)
    , cone_detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _image_header_type;
  _image_header_type image_header;

   typedef std::vector< ::fsd_common_msgs::YoloCone_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::fsd_common_msgs::YoloCone_<ContainerAllocator> >> _cone_detections_type;
  _cone_detections_type cone_detections;





  typedef boost::shared_ptr< ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator> const> ConstPtr;

}; // struct YoloConeDetections_

typedef ::fsd_common_msgs::YoloConeDetections_<std::allocator<void> > YoloConeDetections;

typedef boost::shared_ptr< ::fsd_common_msgs::YoloConeDetections > YoloConeDetectionsPtr;
typedef boost::shared_ptr< ::fsd_common_msgs::YoloConeDetections const> YoloConeDetectionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator1> & lhs, const ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.image_header == rhs.image_header &&
    lhs.cone_detections == rhs.cone_detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator1> & lhs, const ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fsd_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e17c30018a8cba08b69b7dc1fb6a6c3d";
  }

  static const char* value(const ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe17c30018a8cba08ULL;
  static const uint64_t static_value2 = 0xb69b7dc1fb6a6c3dULL;
};

template<class ContainerAllocator>
struct DataType< ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fsd_common_msgs/YoloConeDetections";
  }

  static const char* value(const ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"std_msgs/Header image_header\n"
"\n"
"fsd_common_msgs/YoloCone[] cone_detections\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: fsd_common_msgs/YoloCone\n"
"std_msgs/Float32 x                  # center x\n"
"std_msgs/Float32 y                  # center y\n"
"std_msgs/Float32 width              # width\n"
"std_msgs/Float32 height             # height\n"
"\n"
"std_msgs/String color                 # color of cone, 'r' = red, 'b' = blue, 'y' = yellow\n"
"std_msgs/Float32 colorConfidence   	      # confidence of cone detect\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image_header);
      stream.next(m.cone_detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoloConeDetections_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fsd_common_msgs::YoloConeDetections_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image_header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.image_header);
    s << indent << "cone_detections[]" << std::endl;
    for (size_t i = 0; i < v.cone_detections.size(); ++i)
    {
      s << indent << "  cone_detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fsd_common_msgs::YoloCone_<ContainerAllocator> >::stream(s, indent + "    ", v.cone_detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FSD_COMMON_MSGS_MESSAGE_YOLOCONEDETECTIONS_H
