// Generated by gencpp from file fsd_common_msgs/YoloCone.msg
// DO NOT EDIT!


#ifndef FSD_COMMON_MSGS_MESSAGE_YOLOCONE_H
#define FSD_COMMON_MSGS_MESSAGE_YOLOCONE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/String.h>
#include <std_msgs/Float32.h>

namespace fsd_common_msgs
{
template <class ContainerAllocator>
struct YoloCone_
{
  typedef YoloCone_<ContainerAllocator> Type;

  YoloCone_()
    : x()
    , y()
    , width()
    , height()
    , color()
    , colorConfidence()  {
    }
  YoloCone_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , width(_alloc)
    , height(_alloc)
    , color(_alloc)
    , colorConfidence(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _x_type;
  _x_type x;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _y_type;
  _y_type y;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _width_type;
  _width_type width;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _height_type;
  _height_type height;

   typedef  ::std_msgs::String_<ContainerAllocator>  _color_type;
  _color_type color;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _colorConfidence_type;
  _colorConfidence_type colorConfidence;





  typedef boost::shared_ptr< ::fsd_common_msgs::YoloCone_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fsd_common_msgs::YoloCone_<ContainerAllocator> const> ConstPtr;

}; // struct YoloCone_

typedef ::fsd_common_msgs::YoloCone_<std::allocator<void> > YoloCone;

typedef boost::shared_ptr< ::fsd_common_msgs::YoloCone > YoloConePtr;
typedef boost::shared_ptr< ::fsd_common_msgs::YoloCone const> YoloConeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fsd_common_msgs::YoloCone_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fsd_common_msgs::YoloCone_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fsd_common_msgs::YoloCone_<ContainerAllocator1> & lhs, const ::fsd_common_msgs::YoloCone_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.color == rhs.color &&
    lhs.colorConfidence == rhs.colorConfidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fsd_common_msgs::YoloCone_<ContainerAllocator1> & lhs, const ::fsd_common_msgs::YoloCone_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fsd_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fsd_common_msgs::YoloCone_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fsd_common_msgs::YoloCone_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsd_common_msgs::YoloCone_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsd_common_msgs::YoloCone_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsd_common_msgs::YoloCone_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsd_common_msgs::YoloCone_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fsd_common_msgs::YoloCone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6cb33486e6643502ddbc8297e8d043a";
  }

  static const char* value(const ::fsd_common_msgs::YoloCone_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6cb33486e664350ULL;
  static const uint64_t static_value2 = 0x2ddbc8297e8d043aULL;
};

template<class ContainerAllocator>
struct DataType< ::fsd_common_msgs::YoloCone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fsd_common_msgs/YoloCone";
  }

  static const char* value(const ::fsd_common_msgs::YoloCone_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fsd_common_msgs::YoloCone_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32 x                  # center x\n"
"std_msgs/Float32 y                  # center y\n"
"std_msgs/Float32 width              # width\n"
"std_msgs/Float32 height             # height\n"
"\n"
"std_msgs/String color                 # color of cone, 'r' = red, 'b' = blue, 'y' = yellow\n"
"std_msgs/Float32 colorConfidence   	      # confidence of cone detect\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::fsd_common_msgs::YoloCone_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fsd_common_msgs::YoloCone_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.color);
      stream.next(m.colorConfidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoloCone_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fsd_common_msgs::YoloCone_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fsd_common_msgs::YoloCone_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.y);
    s << indent << "width: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.height);
    s << indent << "color: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.color);
    s << indent << "colorConfidence: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.colorConfidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FSD_COMMON_MSGS_MESSAGE_YOLOCONE_H
