// Generated by gencpp from file fsd_common_msgs/YoloConeTrack.msg
// DO NOT EDIT!


#ifndef FSD_COMMON_MSGS_MESSAGE_YOLOCONETRACK_H
#define FSD_COMMON_MSGS_MESSAGE_YOLOCONETRACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/String.h>
#include <std_msgs/Float32.h>
#include <geometry_msgs/Point.h>
#include <std_msgs/Float32.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/String.h>
#include <std_msgs/UInt8.h>

namespace fsd_common_msgs
{
template <class ContainerAllocator>
struct YoloConeTrack_
{
  typedef YoloConeTrack_<ContainerAllocator> Type;

  YoloConeTrack_()
    : x()
    , y()
    , width()
    , height()
    , color()
    , colorConfidence()
    , position()
    , poseConfidence()
    , tracking_id()
    , tracking_state()
    , missing_frams()  {
    }
  YoloConeTrack_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , width(_alloc)
    , height(_alloc)
    , color(_alloc)
    , colorConfidence(_alloc)
    , position(_alloc)
    , poseConfidence(_alloc)
    , tracking_id(_alloc)
    , tracking_state(_alloc)
    , missing_frams(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float32_<ContainerAllocator>  _x_type;
  _x_type x;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _y_type;
  _y_type y;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _width_type;
  _width_type width;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _height_type;
  _height_type height;

   typedef  ::std_msgs::String_<ContainerAllocator>  _color_type;
  _color_type color;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _colorConfidence_type;
  _colorConfidence_type colorConfidence;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _poseConfidence_type;
  _poseConfidence_type poseConfidence;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _tracking_id_type;
  _tracking_id_type tracking_id;

   typedef  ::std_msgs::String_<ContainerAllocator>  _tracking_state_type;
  _tracking_state_type tracking_state;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _missing_frams_type;
  _missing_frams_type missing_frams;





  typedef boost::shared_ptr< ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator> const> ConstPtr;

}; // struct YoloConeTrack_

typedef ::fsd_common_msgs::YoloConeTrack_<std::allocator<void> > YoloConeTrack;

typedef boost::shared_ptr< ::fsd_common_msgs::YoloConeTrack > YoloConeTrackPtr;
typedef boost::shared_ptr< ::fsd_common_msgs::YoloConeTrack const> YoloConeTrackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator1> & lhs, const ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.color == rhs.color &&
    lhs.colorConfidence == rhs.colorConfidence &&
    lhs.position == rhs.position &&
    lhs.poseConfidence == rhs.poseConfidence &&
    lhs.tracking_id == rhs.tracking_id &&
    lhs.tracking_state == rhs.tracking_state &&
    lhs.missing_frams == rhs.missing_frams;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator1> & lhs, const ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fsd_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d0c6c369c7fbde2a67f35f8e09d52e2";
  }

  static const char* value(const ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d0c6c369c7fbde2ULL;
  static const uint64_t static_value2 = 0xa67f35f8e09d52e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fsd_common_msgs/YoloConeTrack";
  }

  static const char* value(const ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float32 x                  # center x\n"
"std_msgs/Float32 y                  # center y\n"
"std_msgs/Float32 width              # width\n"
"std_msgs/Float32 height             # height\n"
"\n"
"std_msgs/String color                 # color of cone, 'r' = red, 'b' = blue, 'y' = yellow\n"
"std_msgs/Float32 colorConfidence   	      # confidence of cone detect\n"
"\n"
"geometry_msgs/Point position # 3d position with (x,y,z)\n"
"std_msgs/Float32 poseConfidence\n"
"\n"
"std_msgs/UInt8 tracking_id\n"
"std_msgs/String tracking_state # OFF, OK, SEARCHING, TERMINATE\n"
"std_msgs/UInt8 missing_frams\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/UInt8\n"
"uint8 data\n"
;
  }

  static const char* value(const ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.color);
      stream.next(m.colorConfidence);
      stream.next(m.position);
      stream.next(m.poseConfidence);
      stream.next(m.tracking_id);
      stream.next(m.tracking_state);
      stream.next(m.missing_frams);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoloConeTrack_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fsd_common_msgs::YoloConeTrack_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.y);
    s << indent << "width: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.height);
    s << indent << "color: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.color);
    s << indent << "colorConfidence: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.colorConfidence);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "poseConfidence: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.poseConfidence);
    s << indent << "tracking_id: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.tracking_id);
    s << indent << "tracking_state: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.tracking_state);
    s << indent << "missing_frams: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.missing_frams);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FSD_COMMON_MSGS_MESSAGE_YOLOCONETRACK_H
