// Generated by gencpp from file turtle_control/TurtleVelocity.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROL_MESSAGE_TURTLEVELOCITY_H
#define TURTLE_CONTROL_MESSAGE_TURTLEVELOCITY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_control
{
template <class ContainerAllocator>
struct TurtleVelocity_
{
  typedef TurtleVelocity_<ContainerAllocator> Type;

  TurtleVelocity_()
    : linear(0.0)  {
    }
  TurtleVelocity_(const ContainerAllocator& _alloc)
    : linear(0.0)  {
  (void)_alloc;
    }



   typedef float _linear_type;
  _linear_type linear;





  typedef boost::shared_ptr< ::turtle_control::TurtleVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_control::TurtleVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleVelocity_

typedef ::turtle_control::TurtleVelocity_<std::allocator<void> > TurtleVelocity;

typedef boost::shared_ptr< ::turtle_control::TurtleVelocity > TurtleVelocityPtr;
typedef boost::shared_ptr< ::turtle_control::TurtleVelocity const> TurtleVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_control::TurtleVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_control::TurtleVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_control::TurtleVelocity_<ContainerAllocator1> & lhs, const ::turtle_control::TurtleVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.linear == rhs.linear;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_control::TurtleVelocity_<ContainerAllocator1> & lhs, const ::turtle_control::TurtleVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control::TurtleVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control::TurtleVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_control::TurtleVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_control::TurtleVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control::TurtleVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control::TurtleVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_control::TurtleVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aeedbad760b28cbccafc1668ae4ed22c";
  }

  static const char* value(const ::turtle_control::TurtleVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaeedbad760b28cbcULL;
  static const uint64_t static_value2 = 0xcafc1668ae4ed22cULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_control::TurtleVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_control/TurtleVelocity";
  }

  static const char* value(const ::turtle_control::TurtleVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_control::TurtleVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 linear\n"
;
  }

  static const char* value(const ::turtle_control::TurtleVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_control::TurtleVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_control::TurtleVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_control::TurtleVelocity_<ContainerAllocator>& v)
  {
    s << indent << "linear: ";
    Printer<float>::stream(s, indent + "  ", v.linear);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CONTROL_MESSAGE_TURTLEVELOCITY_H
